// brand get
export const GET_BRAND_REQ = 'GET_BRAND_REQ';
export const GET_BRAND_FULFILL = 'GET_BRAND_FULFILL';
export const GET_BRAND_REJECTED = 'GET_BRAND_REJECTED';

// brand create
export const CREATE_BRAND_FULFILL = 'CREATE_BRAND_FULFILL';
export const CREATE_BRAND_REJECTED = 'CREATE_BRAND_REJECTED';

// brand delete
export const DELETE_BRAND_FULFILL = 'DELETE_BRAND_FULFILL';
export const DELETE_BRAND_REJECTED = 'DELETE_BRAND_REJECTED';
