/**
 * brand get
 */
export const GET_BRAND_REQ = 'GET_BRAND_REQ';
export const GET_BRAND_FULFILL = 'GET_BRAND_FULFILL';
export const GET_BRAND_REJECTED = 'GET_BRAND_REJECTED';

// brand create
export const CREATE_BRAND_FULFILL = 'CREATE_BRAND_FULFILL';
export const CREATE_BRAND_REJECTED = 'CREATE_BRAND_REJECTED';

// brand delete
export const DELETE_BRAND_FULFILL = 'DELETE_BRAND_FULFILL';
export const DELETE_BRAND_REJECTED = 'DELETE_BRAND_REJECTED';

// brand status
export const BRAND_STATUS_FULFILL = 'BRAND_STATUS_FULFILL';
export const BRAND_STATUS_REJECTED = 'BRAND_STATUS_REJECTED';

// brand update
export const BRAND_UPDATE_FULFILL = 'BRAND_UPDATE_FULFILL';
export const BRAND_UPDATE_REJECTED = 'BRAND_UPDATE_REJECTED';

/**
 * Tag get
 */
export const GET_TAG_FULFILL = 'GET_TAG_FULFILL';
export const GET_TAG_REJECTED = 'GET_TAG_REJECTED';

// tag create
export const CREATE_TAG_FULFILL = 'CREATE_TAG_FULFILL';
export const CREATE_TAG_REJECTED = 'CREATE_TAG_REJECTED';

// tag update
export const TAG_UPDATE_FULFILL = 'TAG_UPDATE_FULFILL';
export const TAG_UPDATE_REJECTED = 'TAG_UPDATE_REJECTED';

// tag status
export const TAG_STATUS_FULFILL = 'TAG_STATUS_FULFILL';
export const TAG_STATUS_REJECTED = 'TAG_STATUS_REJECTED';

// tag delete
export const DELETE_TAG_FULFILL = 'DELETE_TAG_FULFILL';
export const DELETE_TAG_REJECTED = 'DELETE_TAG_REJECTED';

/**
 * category get -d
 */
export const GET_CATEGORY_REQ = 'GET_CATEGORY_REQ';
export const GET_CATEGORY_FULFILL = 'GET_CATEGORY_FULFILL';
export const GET_CATEGORY_REJECTED = 'GET_CATEGORY_REJECTED';

// category create -d
export const CREATE_CATEGORY_FULFILL = 'CREATE_CATEGORY_FULFILL';
export const CREATE_CATEGORY_REJECTED = 'CREATE_CATEGORY_REJECTED';

// category delete -d
export const DELETE_CATEGORY_FULFILL = 'DELETE_CATEGORY_FULFILL';
export const DELETE_CATEGORY_REJECTED = 'DELETE_CATEGORY_REJECTED';

// category status -d
export const CATEGORY_STATUS_FULFILL = 'CATEGORY_STATUS_FULFILL';
export const CATEGORY_STATUS_REJECTED = 'CATEGORY_STATUS_REJECTED';

// category update -nd
export const CATEGORY_UPDATE_FULFILL = 'CATEGORY_UPDATE_FULFILL';
export const CATEGORY_UPDATE_REJECTED = 'CATEGORY_UPDATE_REJECTED';

/**
 * products get -nd
 */
export const GET_PRODUCT_REQ = 'GET_PRODUCT_REQ';
export const GET_PRODUCT_FULFILL = 'GET_PRODUCT_FULFILL';
export const GET_PRODUCT_REJECTED = 'GET_PRODUCT_REJECTED';

// category create -nd
export const CREATE_PRODUCT_FULFILL = 'CREATE_PRODUCT_FULFILL';
export const CREATE_PRODUCT_REJECTED = 'CREATE_PRODUCT_REJECTED';

// category delete -nd
export const DELETE_PRODUCT_FULFILL = 'DELETE_PRODUCT_FULFILL';
export const DELETE_PRODUCT_REJECTED = 'DELETE_PRODUCT_REJECTED';

// category status -nd
export const PRODUCT_STATUS_FULFILL = 'PRODUCT_STATUS_FULFILL';
export const PRODUCT_STATUS_REJECTED = 'PRODUCT_STATUS_REJECTED';

// category update -nd
export const PRODUCT_UPDATE_FULFILL = 'PRODUCT_UPDATE_FULFILL';
export const PRODUCT_UPDATE_REJECTED = 'PRODUCT_UPDATE_REJECTED';
